# Generated by Django 5.1.2 on 2024-10-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hexaModelWeight',
            fields=[
                ('user_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('heart_seg', models.CharField(default='heartseg.pth', max_length=50)),
                ('lung_seg', models.CharField(default='lungseg.pth', max_length=50)),
                ('liver_seg', models.CharField(default='liverseg.pth', max_length=50)),
                ('spine_seg', models.CharField(default='spineseg.pth', max_length=50)),
                ('breast_seg', models.CharField(default='breastseg.pth', max_length=50)),
                ('thyroid_seg', models.CharField(default='thyroidseg.pth', max_length=50)),
            ],
            options={
                'db_table': 'model_weight',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='hexaOrder',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='UserName', max_length=50)),
                ('project_name', models.CharField(db_column='ProjectName', max_length=50)),
                ('datetime', models.DateTimeField(auto_now_add=True, db_column='DateTime')),
                ('algorithms', models.IntegerField(db_column='Algorithms', default=0)),
                ('success', models.IntegerField(db_column='Success', default=0)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='hexaServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=20)),
                ('port', models.IntegerField()),
            ],
            options={
                'db_table': 'servers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='hexaSessionUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peer', models.CharField(max_length=50)),
                ('user_name', models.CharField(default='NULL', max_length=50)),
                ('session_time', models.DateTimeField(auto_now_add=True)),
                ('duplicated', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'session_users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='hexaUser',
            fields=[
                ('user', models.CharField(db_column='User', default='NULL', max_length=50, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(db_column='Password', default='NULL', max_length=256)),
                ('level', models.IntegerField(db_column='Level', default=0)),
                ('serial_number', models.CharField(db_column='SerialNumber', default='HCYYYYMMDD-NNNN', max_length=50)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
